Feature/detailed filters
janaRicarda/emotion-tracker pull request #43
Opened 2024-05-14 10:02 UTC by JanPSchwarz

2024-05-15 09:10 UTC, benediktbrenk commented on pages/emotion-records.js
>        <StyledPageHeader>
The name StyledPageHeader seems a bit misleading to me. You already have a Header component in the layout. The name (Styled)FilterSection seems more appropriate to me from what code it contains.

2024-05-15 09:28 UTC, benediktbrenk requested changes
The functionality and logic is convincing! 

I've some regards concerning structure. As a suggestion: You could use components in seperate files (Filter/index.js + Filter/Filter.styled.js) if parts of the code belong together as a logical unit. This will improve orientation and readability in your emotion-records.js code enormously.

-> Create a component for the calendar modal
-> Create a component for the filter section

In any case: Please change the name of the StyledPageHeader (l.99) to a more functional naming.

2024-05-15 10:42 UTC, JanPSchwarz commented
> The functionality and logic is convincing!
> 
> I've some regards concerning structure. As a suggestion: You could use components in seperate files (Filter/index.js + Filter/Filter.styled.js) if parts of the code belong together as a logical unit. This will improve orientation and readability in your emotion-records.js code enormously.
> 
> -> Create a component for the calendar modal -> Create a component for the filter section
> 
> In any case: Please change the name of the StyledPageHeader (l.99) to a more functional naming.

Thanks for your review! I will for sure change the StyledPageHeader according to your suggestion and i will consider refactoring to smaller components

2024-05-16 06:32 UTC, JanPSchwarz commented
After last PR i decided to restructure a bit more and changed the `searchBar` to be `FilterEmotionEntries` which holds all filter functions and the `DayPicker` as a separate component

2024-05-16 06:39 UTC, benediktbrenk approved these changes

2024-05-16 09:02 UTC, merged