Feature/backend
janaRicarda/emotion-tracker pull request #69
Opened 2024-05-31 10:40 UTC by JanPSchwarz

2024-06-03 09:29 UTC, FelineHuhn requested changes
Great backend implementation and in general such a good progress! 🥳🤩

I left you some thoughts and suggestions below :)

2024-06-03 09:29 UTC, FelineHuhn commented on pages/_app.js
> +        console.log("Adding item failed");
```suggestion
        console.error("Adding item failed");
```
Using console.error here would be more appropriate for logging errors, or?

2024-06-03 09:29 UTC, FelineHuhn commented on pages/_app.js
> +        console.log("Updating item failed");
```suggestion
        console.error("Updating item failed");
```

2024-06-03 09:29 UTC, FelineHuhn commented on pages/_app.js
> +        console.log("Updating item failed");
```suggestion
        console.error("Updating item failed");
```

2024-06-03 09:29 UTC, FelineHuhn commented on pages/_app.js
> +        console.log("Deleting item failed");
```suggestion
        console.error("Deleting item failed");
```

2024-06-03 09:29 UTC, FelineHuhn commented on pages/api/emotionEntries/[id]/index.js
You could add a try...catch block to ensure that errors are handled properly and appropriate error responses are returned.

2024-06-03 09:29 UTC, FelineHuhn commented on pages/api/emotionEntries/index.js
> +      console.log(error);
```suggestion
      console.error(error);
```

2024-06-03 09:29 UTC, FelineHuhn commented on pages/create/[slug]/index.js
> +  const { data: correspondingEntryFromMongo, isLoading } = useSWR(
Also here I personally would prefer another naming like correspondingDbEmotionEntry, but that's of course a matter of taste.

2024-06-03 09:29 UTC, FelineHuhn commented on pages/index.js
> +  const newest_ID = emotionEntries[emotionEntries.length - 1]._id;
Since we always want to use camelCase for variable naming, you could think about a more appropriate name, e.g. newestEntryId / latestEntryId ...

2024-06-03 10:35 UTC, JanPSchwarz commented
Thanks for the review, i changed all requests!

2024-06-03 13:03 UTC, Braun-Johannes requested changes
Great work!
I commented on the lines i would build a try-catch block in. i do not know if this is needed on this part of the code. 
Also on the already existing try-catch blocks i would change the console.log to console.error.

2024-06-04 06:07 UTC, JanPSchwarz commented
thanks, i had a quick research and i think its reasonable to add `try/catch` blocks on the `fetch` functions in `_app.js` because it  also gives information when server completely rejects your request while `response.ok` gives information about actual server errors like 404 or 500.... so far my understanding. Thanks for the suggestions

2024-06-04 06:46 UTC, FelineHuhn approved these changes
Great improvement - LGTM 🚀

2024-06-04 08:41 UTC, merged